---
#- name: go get kraken
#  shell: "go get {{ kr_url }}"
#  args:
#    creates: "{{ kr_build }}"

- name: go get kraken
  git:
    repo: "{{ kr_repo }}"
    dest: "{{ kr_src_dir }}"
    version: "{{ kr_repo_version }}"

- name: Build kraken-build
  shell: "go build {{ kr_build }}.go"
  args:
    creates: "{{ kr_build }}"
    chdir: "{{ kr_src_dir }}"

- name: Build kraken
  shell: "./{{ kr_build }} {{ kr_build_args }} -config {{ kr_conf_file }}"
  args:
    creates: "{{ kr_build_dir }}/kraken"
    chdir: "{{ kr_src_dir }}"
